name: Release Archive
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: | # Remove lines containing "logging" from files in directory filters/ if there are any
        find filters/ -type f -exec sed -i '/logging/d' {} \;
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'release.zip'
        directory: '.'
        path: "defaults/ filters/ templates/"
    - name: Create Release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: |
          Release ${{ github.ref }}
        draft: false
        prerelease: false
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
